# Using the base image
FROM ubuntu:22.04

#upgrading and Installing pip 
RUN apt-get update && \
    apt-get install -y python3-pip && \
    pip3 install --upgrade pip
RUN pip3 install prometheus_client==0.11.0 

RUN apt-get update && apt-get install -y 

# Copy the Django project files
COPY . .

# Install the dependencies
RUN pip3 install -r requirements.txt

# RUN python3 app/manage.py makemigrarions
# Run any migrations
RUN python3 app/manage.py migrate

# Expose port 8000 for the Django development server.
EXPOSE 8000

# # Set the entrypoint to run the tests
RUN chmod +x test_entrypoint.sh

ENTRYPOINT ["./test_entrypoint.sh"]