# Use the official Python image as the base image
FROM python:3.9-slim-buster

# Copy the requirements file into the container
COPY requirements.txt .

# Install the dependencies
RUN pip install -r requirements.txt

# Copy the Django project files
COPY . /app

# Set the working directory to /app

#WORKDIR /app/

RUN ls .

# Run any migrations
RUN python manage.py migrate

# Set the entrypoint to run the tests
ENTRYPOINT ["python", "manage.py", "test"]
