# Generated by Django 5.1 on 2024-09-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0003_auto_20230425_1944"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
